# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filterPatternLabel = QtWidgets.QLabel(self.centralwidget)
        self.filterPatternLabel.setObjectName("filterPatternLabel")
        self.horizontalLayout_2.addWidget(self.filterPatternLabel)
        self.filterPatternEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.filterPatternEdit.setClearButtonEnabled(False)
        self.filterPatternEdit.setObjectName("filterPatternEdit")
        self.horizontalLayout_2.addWidget(self.filterPatternEdit)
        self.filterSyntaxLabel = QtWidgets.QLabel(self.centralwidget)
        self.filterSyntaxLabel.setObjectName("filterSyntaxLabel")
        self.horizontalLayout_2.addWidget(self.filterSyntaxLabel)
        self.filterSyntaxComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.filterSyntaxComboBox.setObjectName("filterSyntaxComboBox")
        self.filterSyntaxComboBox.addItem("")
        self.filterSyntaxComboBox.addItem("")
        self.filterSyntaxComboBox.addItem("")
        self.filterSyntaxComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.filterSyntaxComboBox)
        self.filterColumnLabel = QtWidgets.QLabel(self.centralwidget)
        self.filterColumnLabel.setObjectName("filterColumnLabel")
        self.horizontalLayout_2.addWidget(self.filterColumnLabel)
        self.filterColumnComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.filterColumnComboBox.setObjectName("filterColumnComboBox")
        self.filterColumnComboBox.addItem("")
        self.filterColumnComboBox.addItem("")
        self.filterColumnComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.filterColumnComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.caseSensitiveFilterCB = QtWidgets.QCheckBox(self.centralwidget)
        self.caseSensitiveFilterCB.setObjectName("caseSensitiveFilterCB")
        self.horizontalLayout.addWidget(self.caseSensitiveFilterCB)
        self.caseSensitiveSortingCB = QtWidgets.QCheckBox(self.centralwidget)
        self.caseSensitiveSortingCB.setObjectName("caseSensitiveSortingCB")
        self.horizontalLayout.addWidget(self.caseSensitiveSortingCB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 651, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Searchable Tree"))
        self.filterPatternLabel.setText(_translate("MainWindow", "Filter pattern:"))
        self.filterSyntaxLabel.setText(_translate("MainWindow", "Filter syntax:"))
        self.filterSyntaxComboBox.setItemText(0, _translate("MainWindow", "glob"))
        self.filterSyntaxComboBox.setItemText(1, _translate("MainWindow", "Regular Expression"))
        self.filterSyntaxComboBox.setItemText(2, _translate("MainWindow", "Starts with"))
        self.filterSyntaxComboBox.setItemText(3, _translate("MainWindow", "Ends with"))
        self.filterColumnLabel.setText(_translate("MainWindow", "Filter column:"))
        self.filterColumnComboBox.setItemText(0, _translate("MainWindow", "Both"))
        self.filterColumnComboBox.setItemText(1, _translate("MainWindow", "Title"))
        self.filterColumnComboBox.setItemText(2, _translate("MainWindow", "Summary"))
        self.caseSensitiveFilterCB.setText(_translate("MainWindow", "Case sensitive filter"))
        self.caseSensitiveSortingCB.setText(_translate("MainWindow", "Case sensitive sorting"))
